[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "frpn-polymer"
version = "0.2.0"
description = "Full-Resolution and Cross-Scale Learning for Polymers"
readme = "README.md"
requires-python = ">=3.9"
dynamic = ["dependencies"]

[tool.setuptools.dynamic]
dependencies = {file = ["reproduce/configs/requirements.txt"]}

[tool.setuptools.packages.find]
where = ["src"]
include = ["frpn*"]
